-- Migration: add missing enum values
-- Adds CREATE_HEADADMIN (was in schema but missing from DB), REVOKE_TOKEN_SUPERADMIN, DELETE_ADMIN

ALTER TYPE "JenisRequest" ADD VALUE IF NOT EXISTS 'CREATE_HEADADMIN';
ALTER TYPE "JenisRequest" ADD VALUE IF NOT EXISTS 'REVOKE_TOKEN_SUPERADMIN';
ALTER TYPE "AksiAdmin" ADD VALUE IF NOT EXISTS 'DELETE_ADMIN';
